package Reports;

import FilesFounder.FileAsString;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Home
 */
public class GenerateReports {

    ArrayList<FileResults> arr = new ArrayList<FileResults>();
    private ArrayList<FileAsString> fileCode = new ArrayList<FileAsString>();
    String firstHalf1;
    String firstHalf2;

    String testingReport;

    String secondHalf;
    String secondHalf2;
    String mutationReport;
    String footer;
    String myStyleCss;
    String bootstrapCss;
    String aboutPage;
    DecimalFormat df;

    public GenerateReports(String totalTime, String avgTimePerMutant) {
        df = new DecimalFormat("#.##");
        firstHalf1 = "<!DOCTYPE html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "<head>\n"
                + "    <meta charset=\"utf-8\" />\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\n"
                + "    <meta name=\"description\" content=\"\" />\n"
                + "    <meta name=\"author\" content=\"\" />\n"
                + "    <title>MuHybApps Report</title>\n"
                + "    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n"
                + "    <link href=\"assets/css/style.css\" rel=\"stylesheet\" />\n"
                + "<script type=\"text/javascript\" src=\"https:\\www.gstatic.com/charts/loader.js\"></script>\n";

        firstHalf2 = " </head>\n"
                + "<body>\n"
                + "    <div class=\"navbar navbar-inverse set-radius-zero\" >\n"
                + "        <div class=\"container\">\n"
                + "            <div class=\"navbar-header\">\n"
                + "                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n"
                + "                    <span class=\"icon-bar\"></span>\n"
                + "                    <span class=\"icon-bar\"></span>\n"
                + "                    <span class=\"icon-bar\"></span>\n"
                + "                </button>\n"
                + "                <span class=\"navbar-brand\">\n"
                + "\n"
                + "                    <!-- <img src=\"assets/img/logo.png\" /> -->\n"
                + "                  <a href=\"Report.html\"><h1>MuHybApps</h1></a>\n"
                + "                </span>\n"
                + "\n"
                + "            </div>\n"
                + "\n"
                + "        </div>\n"
                + "    </div>\n"
                + "    <!-- LOGO HEADER END-->\n"
                + "    <section class=\"menu-section\">\n"
                + "        <div class=\"container\">\n"
                + "            <div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                    <div class=\"navbar-collapse collapse \">\n"
                + "                        <ul id=\"menu-top\" class=\"nav navbar-nav navbar-right\">\n"
                + "                            <li><a href=\"Report.html\">Mutation Report</a></li>\n"
                + "                            <li><a href=\"About.html\" > About</a></li>\n"
                + "\n"
                + "                        </ul>\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "     <!-- MENU SECTION END-->\n"
                + "    <div class=\"content-wrapper\">\n"
                + "         <div class=\"container\">\n"
                + "        <div class=\"row pad-botm\">\n"
                + "            <div class=\"col-md-12\">\n"
                + "                <h4 class=\"header-line\">Mutation Report</h4>\n"
                + "                \n"
                + "                            </div>\n"
                + "\n"
                + "        </div>\n"
                + "		\n"
                + "			<div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                    <!-- Advanced Tables -->\n"
                + "                    <div class=\"panel panel-default\">\n"
                + "                        <div class=\"panel-heading\">\n"
                + "                             Test Results\n"
                + "                        </div>\n"
                + "                        <div class=\"panel-body\">\n"
                + "                            <div class=\"table-responsive\">\n"
                + "                                <table class=\"table table-striped table-bordered table-hover\" >\n"
                + "                                    <thead>\n"
                + "                                        <tr>\n"
                + "                                            <th>File Name</th>\n"
                + "                                            <th>Number of test Cases</th>\n"
                + "                                            <th>Executed</th>\n"
                + "                                            <th>Successe</th>\n"
                + "                                            <th>Failed</th>\n"
                + "					    <th>Skipped</th>\n"
                + "					    <th>Test Score</th>\n"
                + "                                        </tr>\n"
                + "                                    </thead>\n"
                + "                                    <tbody>";

        secondHalf = "</tbody>\n"
                + "                                </table>\n"
                + "                            </div>\n"
                + "                            \n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <!--End Advanced Tables -->\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                    <!-- Advanced Tables -->\n"
                + "                    <div class=\"panel panel-default\">\n"
                + "                        <div class=\"panel-heading\">\n"
                + "                             Mutation Statistics \n"
                + "                        </div>\n"
                + "<h1 ALIGN=\"center\">Mutation Score: ";
        secondHalf2 = "%  </h1>\n"
                + "<h2 ALIGN=\"center\"> Total testing time: " + totalTime + "</h2>"
                + "<h2 ALIGN=\"center\"> Average time per mutant: " + avgTimePerMutant + "</h2>"
                + "						<table class=\"table table-striped\" style=\"border-collapse: collapse;\">\n"
                + "						\n"
                + "						<tbody>\n"
                + "						<tr>\n"
                + "						<th >\n"
                + "							<div id=\"piechart\" style=\"width: 550px; height: 350px;\"></div>\n"
                + "						</th>\n"
                + "						<th>\n"
                + "						<div id=\"piechart2\" style=\"width: 550px; height: 350px;\"></div>\n"
                + "						</th>\n"
                + "						</tr>\n"
                + "						</tbody>\n"
                + "						</table>"
                + "                        <div class=\"panel-body\">\n"
                + "                            <div class=\"table-responsive\">\n"
                + "                                <table class=\"table table-striped table-bordered table-hover\" >\n"
                + "                                    <thead>\n"
                + "                                        <tr>\n"
                + "                                            <th>File Name</th>\n"
                + "                                            <th>Killed Mutants</th>\n"
                + "                                            <th>Survived Mutants</th>\n"
                + "                                            <th>Exceptions</th>\n"
                + "                                            <th>Discarded</th>\n"
                + "					    <th>Total Mutants</th>\n"
                + "					    <th>Mutation Score</th>\n"
                + "                                        </tr>\n"
                + "                                    </thead>\n"
                + "                                    <tbody>";
        footer = "</tbody>\n"
                + "                                </table>\n"
                + "                            </div>\n"
                + "                            \n"
                + "							<div id=\"columnchart_values\" style=\"width: 900px; height: 300px;\"></div>\n"
                + "		</br>\n"
                + "</br>\n"
                + "</br>\n"
                + "</br>	"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <!--End Advanced Tables -->\n"
                + "                </div>\n"
                + "            </div>\n"
                + "                <!-- /. ROW  -->\n"
                + "            \n"
                + "                <!-- /. ROW  -->\n"
                + "            \n"
                + "    </div>\n"
                + "    </div>\n"
                + "     <!-- CONTENT-WRAPPER SECTION END-->\n"
                + "    <section class=\"footer-section\">\n"
                + "        <div class=\"container\">\n"
                + "            <div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                   &copy; 2019 MuHypApps | Designed by : Shazly Magdy\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "</body>\n"
                + "</html>";
        myStyleCss = ".badge {\n"
                + "  padding: 1px 9px 2px;\n"
                + "  font-size: 12.025px;\n"
                + "  font-weight: bold;\n"
                + "  white-space: nowrap;\n"
                + "  color: #ffffff;\n"
                + "  background-color: #999999;\n"
                + "  -webkit-border-radius: 9px;\n"
                + "  -moz-border-radius: 9px;\n"
                + "  border-radius: 9px;\n"
                + "}\n"
                + ".badge:hover {\n"
                + "  color: #ffffff;\n"
                + "  text-decoration: none;\n"
                + "  cursor: pointer;\n"
                + "}\n"
                + ".badge-error {\n"
                + "  background-color: #DC3912;\n"
                + "}\n"
                + ".badge-error:hover {\n"
                + "  background-color: #953b39;\n"
                + "}\n"
                + ".badge-warning {\n"
                + "  background-color: #FF9900;\n"
                + "}\n"
                + ".badge-warning:hover {\n"
                + "  background-color: #c67605;\n"
                + "}\n"
                + ".badge-success {\n"
                + "  background-color: #109618;\n"
                + "}\n"
                + ".badge-success:hover {\n"
                + "  background-color: #356635;\n"
                + "}\n"
                + ".badge-info {\n"
                + "  background-color: #3366CC;\n"
                + "}\n"
                + ".badge-info:hover {\n"
                + "  background-color: #2d6987;\n"
                + "}\n"
                + ".badge-inverse {\n"
                + "  background-color: #333333;\n"
                + "}\n"
                + ".badge-inverse:hover {\n"
                + "  background-color: #1a1a1a;\n"
                + "}"
                + ".tooltip {\n"
                + "    display:inline-block;\n"
                + "    position:relative;\n"
                + "    border-bottom:1px dotted #666;\n"
                + "    text-align:left;\n"
                + "}\n"
                + "\n"
                + ".tooltip .top {\n"
                + "    min-width:200px; \n"
                + "    top:-20px;\n"
                + "    left:50%;\n"
                + "    transform:translate(-50%, -100%);\n"
                + "    padding:10px 20px;\n"
                + "    color:#000000;\n"
                + "    background-color:#EEE;\n"
                + "    font-weight:normal;\n"
                + "    font-size:13px;\n"
                + "    border-radius:8px;\n"
                + "    position:absolute;\n"
                + "    z-index:99999999;\n"
                + "    box-sizing:border-box;\n"
                + "    box-shadow:0 1px 8px rgba(0,0,0,0.5);\n"
                + "    display:none;\n"
                + "}\n"
                + "\n"
                + ".tooltip:hover .top {\n"
                + "    display:block;\n"
                + "}\n"
                + "\n"
                + ".tooltip .top i {\n"
                + "    position:absolute;\n"
                + "    top:100%;\n"
                + "    left:50%;\n"
                + "    margin-left:-12px;\n"
                + "    width:24px;\n"
                + "    height:12px;\n"
                + "    overflow:hidden;\n"
                + "}\n"
                + "\n"
                + ".tooltip .top i::after {\n"
                + "    content:'';\n"
                + "    position:absolute;\n"
                + "    width:12px;\n"
                + "    height:12px;\n"
                + "    left:50%;\n"
                + "    transform:translate(-50%,-50%) rotate(45deg);\n"
                + "    background-color:#EEE;\n"
                + "    box-shadow:0 1px 8px rgba(0,0,0,0.5);\n"
                + "}\n"
                + "\n"
                + "pre{\n"
                + "	background-color:#eee;\n"
                + "	overflow:auto;\n"
                + "	margin:0 0 1em;\n"
                + "	padding: .5em 1em;\n"
                + "}\n"
                + "pre code,\n"
                + "pre .line-number {\n"
                + "	color: black;\n"
                + "	display: block;\n"
                + "}\n"
                + "pre .line-number{\n"
                + "	float: left;\n"
                + "	margin: 0 1em 0 -1em;\n"
                + "	border-right: 1px solid;\n"
                + "	text-align: right;\n"
                + "}\n"
                + "\n"
                + "pre .line-number span{\n"
                + "	display: block;\n"
                + "	padding: 0 .5em 0 1em;\n"
                + "}\n"
                + "\n"
                + "pre .cl {\n"
                + "	display:block;\n"
                + "	clear: both;\n"
                + "}\n"
                + "\n"
                + "\n"
                + "\n"
                + "body {\n"
                + "    font-family: 'Open Sans', sans-serif;\n"
                + "    line-height:28px;\n"
                + "   \n"
                + "}\n"
                + ".set-radius-zero {\n"
                + "    border-radius:0px;\n"
                + "    -moz-border-radius:0px;\n"
                + "    -webkit-border-radius:0px;\n"
                + "}\n"
                + ".content-wrapper {\n"
                + "    margin-top: 40px;\n"
                + "    min-height:800px;\n"
                + "    padding-bottom:90px;\n"
                + "}\n"
                + ".header-line {\n"
                + "    font-weight:900;\n"
                + "    padding-bottom:25px;\n"
                + "    border-bottom:1px solid #eeeeee;\n"
                + "    text-transform:uppercase;\n"
                + "}\n"
                + ".pad-botm {\n"
                + "    padding-bottom:30px;\n"
                + "}\n"
                + "\n"
                + ".right-div {\n"
                + "    float: right; \n"
                + "    padding: 20px;\n"
                + "}\n"
                + "#menu-top a {\n"
                + "    color:#000;\n"
                + "    text-decoration:none;\n"
                + "    font-weight:500;\n"
                + "    padding: 25px 15px 25px 15px;\n"
                + "    text-transform:uppercase;\n"
                + "\n"
                + "}\n"
                + ".menu-section {\n"
                + "    background-color: #f7f7f7;\n"
                + "    border-bottom:5px solid #9170E4;\n"
                + "    width:100%\n"
                + "}\n"
                + ".menu-top-active {\n"
                + "    background-color:#eeeeee;\n"
                + "}\n"
                + ".navbar-inverse {\n"
                + "background-color: #FFF;\n"
                + "border-color: rgba(155, 153, 153, 0.23);\n"
                + "\n"
                + "}\n"
                + "\n"
                + ".navbar {\n"
                + "    min-height: 90px;\n"
                + "    margin-bottom: 0px;\n"
                + "   \n"
                + "}\n"
                + ".navbar-inverse .navbar-collapse, .navbar-inverse .navbar-form {\n"
                + "    border-color:transparent;\n"
                + "}\n"
                + ".navbar-toggle {\n"
                + "background-color: black;\n"
                + "border: 1px solid black;\n"
                + "}\n"
                + "\n"
                + ".img-comments {\n"
                + "   border: 3px double #e1e1e1;\n"
                + "height: 60px;\n"
                + "\n"
                + "}\n"
                + "\n"
                + ".chat-widget-main {\n"
                + "    max-height:330px;\n"
                + "    overflow:auto;\n"
                + "}\n"
                + "\n"
                + ".slide-bdr {\n"
                + "   border:5px solid #9170E4\n"
                + "}\n"
                + ".chat-widget-left:after {\n"
                + "    top: 100%;\n"
                + "    left: 10%;\n"
                + "    border: solid transparent;\n"
                + "    content: \" \";\n"
                + "    position: absolute;\n"
                + "    border-top-color: #F70E62;\n"
                + "    border-width: 15px;\n"
                + "    margin-left: -15px;\n"
                + "}\n"
                + "\n"
                + ".chat-widget-left {\n"
                + "    width: 100%;\n"
                + "    height: auto;\n"
                + "    padding: 15px;\n"
                + "    -webkit-border-radius: 5px;\n"
                + "    -moz-border-radius: 5px;\n"
                + "    border-radius: 5px;\n"
                + "    position: relative;\n"
                + "    border: 1px solid #F70E62;\n"
                + "    font-size:12px;\n"
                + "}\n"
                + ".chat-widget-right:after {\n"
                + "    top: 100%;\n"
                + "    right: 10%;\n"
                + "    border: solid transparent;\n"
                + "    content: \" \";\n"
                + "    position: absolute;\n"
                + "    border-top-color: #5AA8CC;\n"
                + "    border-width: 15px;\n"
                + "    margin-left: -15px;\n"
                + "}\n"
                + "\n"
                + ".chat-widget-right {\n"
                + "    width: 100%;\n"
                + "    height: auto;\n"
                + "    padding: 15px;\n"
                + "    -webkit-border-radius: 5px;\n"
                + "    -moz-border-radius: 5px;\n"
                + "    border-radius: 5px;\n"
                + "    position: relative;\n"
                + "    border: 1px solid #5AA8CC;\n"
                + "    font-size:12px;\n"
                + "}\n"
                + "\n"
                + ".chat-widget-name-left {\n"
                + "   color: #808080;\n"
                + "    margin-top: 30px;\n"
                + "    margin-left: 60px;\n"
                + "    text-align:left;\n"
                + "}\n"
                + "\n"
                + "    .img-left-chat {\n"
                + "        border:3px double #e1e1e1;\n"
                + "        float:left;\n"
                + "        margin-right:30px;\n"
                + "    }\n"
                + "     .img-right-chat {\n"
                + "        border:3px double #e1e1e1;\n"
                + "        float:right;\n"
                + "        margin-left:30px;\n"
                + "    }\n"
                + "     .chat-widget-main img-right {\n"
                + "        border:3px double #e1e1e1;\n"
                + "        float:left;\n"
                + "    }\n"
                + ".chat-widget-name-left h4 {\n"
                + "    font-weight:normal;\n"
                + "    font-size:11px;\n"
                + "    \n"
                + "}\n"
                + ".chat-widget-name-left h5 {\n"
                + "    font-weight:normal;\n"
                + "    font-size:10px;\n"
                + "}\n"
                + ".chat-widget-name-right h4 {\n"
                + "    font-weight:normal;\n"
                + "    font-size:11px;\n"
                + "}\n"
                + ".chat-widget-name-right h5 {\n"
                + "    font-weight:normal;\n"
                + "    font-size:10px;\n"
                + "}\n"
                + ".chat-widget-name-right {\n"
                + "    color: #808080;\n"
                + "    margin-top: 40px;\n"
                + "    margin-right: 60px;\n"
                + "    text-align:right;\n"
                + "}\n"
                + "\n"
                + ".recent-users-sec img {\n"
                + "    max-height:80px;\n"
                + "    margin:15px;\n"
                + "}\n"
                + "\n"
                + ".back-widget-set {\n"
                + "    background-color:transparent;\n"
                + "}\n"
                + ".footer-section {\n"
                + "    padding:25px 50px 25px 50px;\n"
                + "    color:#000;\n"
                + "    font-size:13px;\n"
                + "      background-color: #f7f7f7;\n"
                + "      text-align:right;\n"
                + "       border-top:5px solid #9170E4;\n"
                + "\n"
                + "}\n"
                + "\n"
                + "    .footer-section a, .footer-section a:hover {\n"
                + "        color:#000;\n"
                + "    }";
        bootstrapCss = "html {\n"
                + "  font-family: sans-serif;\n"
                + "  -webkit-text-size-adjust: 100%;\n"
                + "      -ms-text-size-adjust: 100%;\n"
                + "}\n"
                + "body {\n"
                + "  margin: 0;\n"
                + "}\n"
                + "article,\n"
                + "aside,\n"
                + "details,\n"
                + "figcaption,\n"
                + "figure,\n"
                + "footer,\n"
                + "header,\n"
                + "hgroup,\n"
                + "main,\n"
                + "nav,\n"
                + "section,\n"
                + "summary {\n"
                + "  display: block;\n"
                + "}\n"
                + "a {\n"
                + "  background: transparent;\n"
                + "}\n"
                + "a:active,\n"
                + "a:hover {\n"
                + "  outline: 0;\n"
                + "}\n"
                + "img {\n"
                + "  border: 0;\n"
                + "}\n"
                + "button,\n"
                + "input,\n"
                + "optgroup,\n"
                + "select,\n"
                + "textarea {\n"
                + "  margin: 0;\n"
                + "  font: inherit;\n"
                + "  color: inherit;\n"
                + "}\n"
                + "button {\n"
                + "  overflow: visible;\n"
                + "}\n"
                + "button,\n"
                + "select {\n"
                + "  text-transform: none;\n"
                + "}\n"
                + "button,\n"
                + "html input[type=\"button\"],\n"
                + "input[type=\"reset\"],\n"
                + "input[type=\"submit\"] {\n"
                + "  -webkit-appearance: button;\n"
                + "  cursor: pointer;\n"
                + "}\n"
                + "table {\n"
                + "  border-spacing: 0;\n"
                + "  border-collapse: collapse;\n"
                + "}\n"
                + "td,\n"
                + "th {\n"
                + "  padding: 0;\n"
                + "}\n"
                + "* {\n"
                + "  -webkit-box-sizing: border-box;\n"
                + "     -moz-box-sizing: border-box;\n"
                + "          box-sizing: border-box;\n"
                + "}\n"
                + "*:before,\n"
                + "*:after {\n"
                + "  -webkit-box-sizing: border-box;\n"
                + "     -moz-box-sizing: border-box;\n"
                + "          box-sizing: border-box;\n"
                + "}\n"
                + "html {\n"
                + "  font-size: 10px;\n"
                + "\n"
                + "  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n"
                + "}\n"
                + "body {\n"
                + "  font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
                + "  font-size: 14px;\n"
                + "  line-height: 1.42857143;\n"
                + "  color: #333;\n"
                + "  background-color: #fff;\n"
                + "}\n"
                + "input,\n"
                + "button,\n"
                + "select,\n"
                + "textarea {\n"
                + "  font-family: inherit;\n"
                + "  font-size: inherit;\n"
                + "  line-height: inherit;\n"
                + "}\n"
                + "a {\n"
                + "  color: #428bca;\n"
                + "  text-decoration: none;\n"
                + "}\n"
                + "a:hover,\n"
                + "a:focus {\n"
                + "  color: #2a6496;\n"
                + "  text-decoration: underline;\n"
                + "}\n"
                + "img {\n"
                + "  vertical-align: middle;\n"
                + "}\n"
                + "h1,\n"
                + "h2,\n"
                + "h3,\n"
                + "h4,\n"
                + "h5,\n"
                + "h6,\n"
                + ".h1,\n"
                + ".h2,\n"
                + ".h3,\n"
                + ".h4,\n"
                + ".h5,\n"
                + ".h6 {\n"
                + "  font-family: inherit;\n"
                + "  font-weight: 500;\n"
                + "  line-height: 1.1;\n"
                + "  color: inherit;\n"
                + "}\n"
                + "h4,\n"
                + ".h4,\n"
                + "h5,\n"
                + ".h5,\n"
                + "h6,\n"
                + ".h6 {\n"
                + "  margin-top: 10px;\n"
                + "  margin-bottom: 10px;\n"
                + "}\n"
                + "h4,\n"
                + ".h4 {\n"
                + "  font-size: 18px;\n"
                + "}\n"
                + "ul,\n"
                + "ol {\n"
                + "  margin-top: 0;\n"
                + "  margin-bottom: 10px;\n"
                + "}\n"
                + ".container {\n"
                + "  padding-right: 15px;\n"
                + "  padding-left: 15px;\n"
                + "  margin-right: auto;\n"
                + "  margin-left: auto;\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .container {\n"
                + "    width: 750px;\n"
                + "  }\n"
                + "}\n"
                + "@media (min-width: 992px) {\n"
                + "  .container {\n"
                + "    width: 970px;\n"
                + "  }\n"
                + "}\n"
                + "@media (min-width: 1200px) {\n"
                + "  .container {\n"
                + "    width: 1170px;\n"
                + "  }\n"
                + "}\n"
                + ".row {\n"
                + "  margin-right: -15px;\n"
                + "  margin-left: -15px;\n"
                + "}\n"
                + ".col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {\n"
                + "  position: relative;\n"
                + "  min-height: 1px;\n"
                + "  padding-right: 15px;\n"
                + "  padding-left: 15px;\n"
                + "}\n"
                + "@media (min-width: 992px) {\n"
                + "  .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12 {\n"
                + "    float: left;\n"
                + "  }\n"
                + "  .col-md-12 {\n"
                + "    width: 100%;\n"
                + "  }\n"
                + "  }\n"
                + "  table {\n"
                + "  background-color: transparent;\n"
                + "}\n"
                + "th {\n"
                + "  text-align: left;\n"
                + "}\n"
                + ".table {\n"
                + "  width: 100%;\n"
                + "  max-width: 100%;\n"
                + "  margin-bottom: 20px;\n"
                + "}\n"
                + ".table > thead > tr > th,\n"
                + ".table > tbody > tr > th,\n"
                + ".table > tfoot > tr > th,\n"
                + ".table > thead > tr > td,\n"
                + ".table > tbody > tr > td,\n"
                + ".table > tfoot > tr > td {\n"
                + "  padding: 8px;\n"
                + "  line-height: 1.42857143;\n"
                + "  vertical-align: top;\n"
                + "  border-top: 1px solid #ddd;\n"
                + "}\n"
                + ".table > thead > tr > th {\n"
                + "  vertical-align: bottom;\n"
                + "  border-bottom: 2px solid #ddd;\n"
                + "}\n"
                + ".table > caption + thead > tr:first-child > th,\n"
                + ".table > colgroup + thead > tr:first-child > th,\n"
                + ".table > thead:first-child > tr:first-child > th,\n"
                + ".table > caption + thead > tr:first-child > td,\n"
                + ".table > colgroup + thead > tr:first-child > td,\n"
                + ".table > thead:first-child > tr:first-child > td {\n"
                + "  border-top: 0;\n"
                + "}\n"
                + ".table-bordered {\n"
                + "  border: 1px solid #ddd;\n"
                + "}\n"
                + ".table-bordered > thead > tr > th,\n"
                + ".table-bordered > tbody > tr > th,\n"
                + ".table-bordered > tfoot > tr > th,\n"
                + ".table-bordered > thead > tr > td,\n"
                + ".table-bordered > tbody > tr > td,\n"
                + ".table-bordered > tfoot > tr > td {\n"
                + "  border: 1px solid #ddd;\n"
                + "}\n"
                + ".table-bordered > thead > tr > th,\n"
                + ".table-bordered > thead > tr > td {\n"
                + "  border-bottom-width: 2px;\n"
                + "}\n"
                + ".table-striped > tbody > tr:nth-child(odd) > td,\n"
                + ".table-striped > tbody > tr:nth-child(odd) > th {\n"
                + "  background-color: #f9f9f9;\n"
                + "}\n"
                + ".table-hover > tbody > tr:hover > td,\n"
                + ".table-hover > tbody > tr:hover > th {\n"
                + "  background-color: #f5f5f5;\n"
                + "}\n"
                + "	@media screen and (max-width: 767px) {\n"
                + "  .table-responsive {\n"
                + "    width: 100%;\n"
                + "    margin-bottom: 15px;\n"
                + "    overflow-x: auto;\n"
                + "    overflow-y: hidden;\n"
                + "    -webkit-overflow-scrolling: touch;\n"
                + "    -ms-overflow-style: -ms-autohiding-scrollbar;\n"
                + "    border: 1px solid #ddd;\n"
                + "  }\n"
                + "  .table-responsive > .table {\n"
                + "    margin-bottom: 0;\n"
                + "  }\n"
                + "  .table-responsive > .table > thead > tr > th,\n"
                + "  .table-responsive > .table > tbody > tr > th,\n"
                + "  .table-responsive > .table > tfoot > tr > th,\n"
                + "  .table-responsive > .table > thead > tr > td,\n"
                + "  .table-responsive > .table > tbody > tr > td,\n"
                + "  .table-responsive > .table > tfoot > tr > td {\n"
                + "    white-space: nowrap;\n"
                + "  }\n"
                + "  .table-responsive > .table-bordered {\n"
                + "    border: 0;\n"
                + "  }\n"
                + "  .table-responsive > .table-bordered > thead > tr > th:first-child,\n"
                + "  .table-responsive > .table-bordered > tbody > tr > th:first-child,\n"
                + "  .table-responsive > .table-bordered > tfoot > tr > th:first-child,\n"
                + "  .table-responsive > .table-bordered > thead > tr > td:first-child,\n"
                + "  .table-responsive > .table-bordered > tbody > tr > td:first-child,\n"
                + "  .table-responsive > .table-bordered > tfoot > tr > td:first-child {\n"
                + "    border-left: 0;\n"
                + "  }\n"
                + "  .table-responsive > .table-bordered > thead > tr > th:last-child,\n"
                + "  .table-responsive > .table-bordered > tbody > tr > th:last-child,\n"
                + "  .table-responsive > .table-bordered > tfoot > tr > th:last-child,\n"
                + "  .table-responsive > .table-bordered > thead > tr > td:last-child,\n"
                + "  .table-responsive > .table-bordered > tbody > tr > td:last-child,\n"
                + "  .table-responsive > .table-bordered > tfoot > tr > td:last-child {\n"
                + "    border-right: 0;\n"
                + "  }\n"
                + "  .table-responsive > .table-bordered > tbody > tr:last-child > th,\n"
                + "  .table-responsive > .table-bordered > tfoot > tr:last-child > th,\n"
                + "  .table-responsive > .table-bordered > tbody > tr:last-child > td,\n"
                + "  .table-responsive > .table-bordered > tfoot > tr:last-child > td {\n"
                + "    border-bottom: 0;\n"
                + "  }\n"
                + "}\n"
                + ".collapse {\n"
                + "  display: none;\n"
                + "}\n"
                + ".nav {\n"
                + "  padding-left: 0;\n"
                + "  margin-bottom: 0;\n"
                + "  list-style: none;\n"
                + "}\n"
                + ".nav > li {\n"
                + "  position: relative;\n"
                + "  display: block;\n"
                + "}\n"
                + ".nav > li > a {\n"
                + "  position: relative;\n"
                + "  display: block;\n"
                + "  padding: 10px 15px;\n"
                + "}\n"
                + ".nav > li > a:hover,\n"
                + ".nav > li > a:focus {\n"
                + "  text-decoration: none;\n"
                + "  background-color: #eee;\n"
                + "}\n"
                + ".navbar {\n"
                + "  position: relative;\n"
                + "  min-height: 50px;\n"
                + "  margin-bottom: 20px;\n"
                + "  border: 1px solid transparent;\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar {\n"
                + "    border-radius: 4px;\n"
                + "  }\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar-header {\n"
                + "    float: left;\n"
                + "  }\n"
                + "}\n"
                + ".navbar-collapse {\n"
                + "  padding-right: 15px;\n"
                + "  padding-left: 15px;\n"
                + "  overflow-x: visible;\n"
                + "  -webkit-overflow-scrolling: touch;\n"
                + "  border-top: 1px solid transparent;\n"
                + "  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .1);\n"
                + "          box-shadow: inset 0 1px 0 rgba(255, 255, 255, .1);\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar-collapse {\n"
                + "    width: auto;\n"
                + "    border-top: 0;\n"
                + "    -webkit-box-shadow: none;\n"
                + "            box-shadow: none;\n"
                + "  }\n"
                + "  .navbar-collapse.collapse {\n"
                + "    display: block !important;\n"
                + "    height: auto !important;\n"
                + "    padding-bottom: 0;\n"
                + "    overflow: visible !important;\n"
                + "  }\n"
                + "}\n"
                + ".container > .navbar-header,\n"
                + ".container-fluid > .navbar-header,\n"
                + ".container > .navbar-collapse,\n"
                + ".container-fluid > .navbar-collapse {\n"
                + "  margin-right: -15px;\n"
                + "  margin-left: -15px;\n"
                + "}\n"
                + "  .container > .navbar-header,\n"
                + "  .container-fluid > .navbar-header,\n"
                + "  .container > .navbar-collapse,\n"
                + "  .container-fluid > .navbar-collapse {\n"
                + "    margin-right: 0;\n"
                + "    margin-left: 0;\n"
                + "  }\n"
                + ".navbar-brand {\n"
                + "  float: left;\n"
                + "  height: 50px;\n"
                + "  padding: 15px 15px;\n"
                + "  font-size: 18px;\n"
                + "  line-height: 20px;\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar > .container .navbar-brand,\n"
                + "  .navbar > .container-fluid .navbar-brand {\n"
                + "    margin-left: -15px;\n"
                + "  }\n"
                + "}\n"
                + ".navbar-toggle {\n"
                + "  position: relative;\n"
                + "  float: right;\n"
                + "  padding: 9px 10px;\n"
                + "  margin-top: 8px;\n"
                + "  margin-right: 15px;\n"
                + "  margin-bottom: 8px;\n"
                + "  background-color: transparent;\n"
                + "  background-image: none;\n"
                + "  border: 1px solid transparent;\n"
                + "  border-radius: 4px;\n"
                + "}\n"
                + ".navbar-toggle:focus {\n"
                + "  outline: 0;\n"
                + "}\n"
                + ".navbar-toggle .icon-bar {\n"
                + "  display: block;\n"
                + "  width: 22px;\n"
                + "  height: 2px;\n"
                + "  border-radius: 1px;\n"
                + "}\n"
                + ".navbar-toggle .icon-bar + .icon-bar {\n"
                + "  margin-top: 4px;\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar-toggle {\n"
                + "    display: none;\n"
                + "  }\n"
                + "}\n"
                + ".navbar-nav {\n"
                + "  margin: 7.5px -15px;\n"
                + "}\n"
                + ".navbar-nav > li > a {\n"
                + "  padding-top: 10px;\n"
                + "  padding-bottom: 10px;\n"
                + "  line-height: 20px;\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar-nav {\n"
                + "    float: left;\n"
                + "    margin: 0;\n"
                + "  }\n"
                + "  .navbar-nav > li {\n"
                + "    float: left;\n"
                + "  }\n"
                + "  .navbar-nav > li > a {\n"
                + "    padding-top: 15px;\n"
                + "    padding-bottom: 15px;\n"
                + "  }\n"
                + "  .navbar-nav.navbar-right:last-child {\n"
                + "    margin-right: -15px;\n"
                + "  }\n"
                + "}\n"
                + "@media (min-width: 768px) {\n"
                + "  .navbar-left {\n"
                + "    float: left !important;\n"
                + "  }\n"
                + "  .navbar-right {\n"
                + "    float: right !important;\n"
                + "  }\n"
                + "}\n"
                + ".navbar-inverse {\n"
                + "  background-color: #222;\n"
                + "  border-color: #080808;\n"
                + "}\n"
                + ".navbar-inverse .navbar-brand {\n"
                + "  color: #777;\n"
                + "}\n"
                + ".navbar-inverse .navbar-toggle {\n"
                + "  border-color: #333;\n"
                + "}\n"
                + ".navbar-inverse .navbar-toggle:hover,\n"
                + ".navbar-inverse .navbar-toggle:focus {\n"
                + "  background-color: #333;\n"
                + "}\n"
                + ".navbar-inverse .navbar-toggle .icon-bar {\n"
                + "  background-color: #fff;\n"
                + "}\n"
                + ".panel {\n"
                + "  margin-bottom: 20px;\n"
                + "  background-color: #fff;\n"
                + "  border: 1px solid transparent;\n"
                + "  border-radius: 4px;\n"
                + "  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, .05);\n"
                + "          box-shadow: 0 1px 1px rgba(0, 0, 0, .05);\n"
                + "}\n"
                + ".panel-body {\n"
                + "  padding: 15px;\n"
                + "}\n"
                + ".panel-heading {\n"
                + "  padding: 10px 15px;\n"
                + "  border-bottom: 1px solid transparent;\n"
                + "  border-top-left-radius: 3px;\n"
                + "  border-top-right-radius: 3px;\n"
                + "}\n"
                + ".panel-default {\n"
                + "  border-color: #ddd;\n"
                + "}\n"
                + ".panel-default > .panel-heading {\n"
                + "  color: #333;\n"
                + "  background-color: #f5f5f5;\n"
                + "  border-color: #ddd;\n"
                + "}\n"
                + ".clearfix:before,\n"
                + ".clearfix:after,\n"
                + ".dl-horizontal dd:before,\n"
                + ".dl-horizontal dd:after,\n"
                + ".container:before,\n"
                + ".container:after,\n"
                + ".container-fluid:before,\n"
                + ".container-fluid:after,\n"
                + ".row:before,\n"
                + ".row:after,\n"
                + ".form-horizontal .form-group:before,\n"
                + ".form-horizontal .form-group:after,\n"
                + ".btn-toolbar:before,\n"
                + ".btn-toolbar:after,\n"
                + ".btn-group-vertical > .btn-group:before,\n"
                + ".btn-group-vertical > .btn-group:after,\n"
                + ".nav:before,\n"
                + ".nav:after,\n"
                + ".navbar:before,\n"
                + ".navbar:after,\n"
                + ".navbar-header:before,\n"
                + ".navbar-header:after,\n"
                + ".navbar-collapse:before,\n"
                + ".navbar-collapse:after,\n"
                + ".pager:before,\n"
                + ".pager:after,\n"
                + ".panel-body:before,\n"
                + ".panel-body:after,\n"
                + ".modal-footer:before,\n"
                + ".modal-footer:after {\n"
                + "  display: table;\n"
                + "  content: \" \";\n"
                + "}\n"
                + ".clearfix:after,\n"
                + ".dl-horizontal dd:after,\n"
                + ".container:after,\n"
                + ".container-fluid:after,\n"
                + ".row:after,\n"
                + ".form-horizontal .form-group:after,\n"
                + ".btn-toolbar:after,\n"
                + ".btn-group-vertical > .btn-group:after,\n"
                + ".nav:after,\n"
                + ".navbar:after,\n"
                + ".navbar-header:after,\n"
                + ".navbar-collapse:after,\n"
                + ".pager:after,\n"
                + ".panel-body:after,\n"
                + ".modal-footer:after {\n"
                + "  clear: both;\n"
                + "}\n"
                + "";
        aboutPage = "<!DOCTYPE html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "<head>\n"
                + "    <meta charset=\"utf-8\" />\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\n"
                + "    <meta name=\"description\" content=\"\" />\n"
                + "    <meta name=\"author\" content=\"\" />\n"
                + "    <!--[if IE]>\n"
                + "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n"
                + "        <![endif]-->\n"
                + "    <title>MuHybApps</title>\n"
                + "    <!-- BOOTSTRAP CORE STYLE  -->\n"
                + "    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n"
                + "    <link href=\"assets/css/style.css\" rel=\"stylesheet\" />\n"
                + "    <!-- GOOGLE FONT    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' /> -->\n"
                + "\n"
                + "\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div class=\"navbar navbar-inverse set-radius-zero\" >\n"
                + "        <div class=\"container\">\n"
                + "            <div class=\"navbar-header\">\n"
                + "                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n"
                + "                    <span class=\"icon-bar\"></span>\n"
                + "                    <span class=\"icon-bar\"></span>\n"
                + "                    <span class=\"icon-bar\"></span>\n"
                + "                </button>\n"
                + "                <span class=\"navbar-brand\" href=\"index.html\">\n"
                + "\n"
                + "                    <!-- <img src=\"assets/img/logo.png\" /> -->\n"
                + "                  <a href=\"Report.html\"><h1>MuHybApps</h1></a>\n"
                + "                </span>\n"
                + "\n"
                + "            </div>\n"
                + "\n"
                + "        </div>\n"
                + "    </div>\n"
                + "    <!-- LOGO HEADER END-->\n"
                + "    <section class=\"menu-section\">\n"
                + "        <div class=\"container\">\n"
                + "            <div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                    <div class=\"navbar-collapse collapse \">\n"
                + "                        <ul id=\"menu-top\" class=\"nav navbar-nav navbar-right\">\n"
                + "                            <li><a href=\"Report.html\">Mutation Report</a></li>\n"
                + "                            <li><a href=\"About.html\" > About</a></li>\n"
                + "\n"
                + "                        </ul>\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "     <!-- MENU SECTION END-->\n"
                + "    <div class=\"content-wrapper\">\n"
                + "         <div class=\"container\">\n"
                + "        <div class=\"row pad-botm\">\n"
                + "            <div class=\"col-md-12\">\n"
                + "                <h4 class=\"header-line\">About</h4>\n"
                + "                \n"
                + "                            </div>\n"
                + "\n"
                + "        </div>\n"
                + "		\n"
                + "\n"
                + "		\n"
                + "            <div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                    <!-- Advanced Tables -->\n"
                + "                    <div class=\"panel panel-default\">\n"
                + "<h1>This Software Made By: Shazly Ahmed</h1>\n"
                + "<h2>Master of Software Engineering</h2>\n"
                + "<h2>Email:smagdy@eelu.edu.eg - shazly.eelu.eg@gmail.com</h2>"
                + "						\n"
                + "                    </div>\n"
                + "                    <!--End Advanced Tables -->\n"
                + "                </div>\n"
                + "            </div>\n"
                + "                <!-- /. ROW  -->\n"
                + "            \n"
                + "                <!-- /. ROW  -->\n"
                + "            \n"
                + "    </div>\n"
                + "    </div>\n"
                + "     <!-- CONTENT-WRAPPER SECTION END-->\n"
                + "    <section class=\"footer-section\">\n"
                + "        <div class=\"container\">\n"
                + "            <div class=\"row\">\n"
                + "                <div class=\"col-md-12\">\n"
                + "                   &copy; 2019 MuHypApps | Designed by : Shazly Magdy\n"
                + "                </div>\n"
                + "\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "</body>\n"
                + "</html>";

    }

    public void generateHtml(String path, ArrayList<Results> arr2, ArrayList<MutationResults> arr, ArrayList<ResultsForEachFile> arr3) {

        File mainFolder = new File(path + "\\Reports");
        File cssFolder = new File(path + "\\Reports\\assets\\css");
        try {

            mainFolder.mkdirs();
            cssFolder.mkdirs();
            mutationReport = printmutationTable(path, arr, arr3);
            GenerateSecondPieGraph gp = new GenerateSecondPieGraph();
            String operatorsPieChart = gp.getPieString(arr3);
            String killedPieChart = "<script type=\"text/javascript\">\n"
                    + "      google.charts.load('current', {'packages':['corechart']});\n"
                    + "      google.charts.setOnLoadCallback(drawChart);\n"
                    + "\n"
                    + "      function drawChart() {\n"
                    + "\n"
                    + "        var data = google.visualization.arrayToDataTable([\n"
                    + "          ['State', 'Number of Mutants'],\n"
                    + "          ['Survived', " + totalSurvived + " ],\n"
                    + "          ['Killed', " + totalKilled + " ],\n"
                    + "          ['Exceptions', " + totalExceptions + " ],\n"
                    + "          ['Discarded', " + totalSyntaxErrors + "  ]\n"
                    + "        ]);\n"
                    + "\n"
                    + "        var options = {\n"
                    + "          title: 'Mutants Statistics'\n"
                    + "        };\n"
                    + "\n"
                    + "        var chart = new google.visualization.PieChart(document.getElementById('piechart'));\n"
                    + "\n"
                    + "        chart.draw(data, options);\n"
                    + "      }\n"
                    + "    </script>\n\n";

            PrintWriter pw = new PrintWriter(mainFolder + "\\Report.html");
            pw.print(firstHalf1);
            GenerateGraphDivMain gg = new GenerateGraphDivMain(path + "\\Reports\\assets\\css");
            String graphHTML = gg.generateScript(arr);
            String MuScore = df.format(mutationScore);

            pw.print(graphHTML);
            pw.print(killedPieChart);
            pw.print(operatorsPieChart);
            pw.print(firstHalf2);

            testingReport = printTable(arr2);
            pw.print(testingReport);
            pw.print(secondHalf);
            pw.print(MuScore);
            pw.print(secondHalf2);
            pw.print(mutationReport);
            pw.print(footer);
            pw.close();
            pw = new PrintWriter(cssFolder + "\\style.css");
            pw.print(myStyleCss);
            pw.close();
            pw = new PrintWriter(cssFolder + "\\bootstrap.css");
            pw.print(bootstrapCss);
            pw.close();
            pw = new PrintWriter(mainFolder + "\\About.html");
            pw.print(aboutPage);
            pw.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(GenerateReports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String printTable(ArrayList<Results> arr) {
        String restString = "";
        for (int i = 0; i < arr.size(); i++) {
            restString += "<tr class=\"odd gradeX\">";
            restString += "<td>" + arr.get(i).getFileName() + "</td>";
            restString += "<td>" + arr.get(i).getOutOf() + "</td>";
            restString += "<td>" + arr.get(i).getExecuted() + "</td>";
            restString += "<td>" + (arr.get(i).getExecuted() - arr.get(i).getNoOfFailed()) + "</td>";
            restString += "<td>" + arr.get(i).getNoOfFailed() + "</td>";
            restString += "<td>" + "Not yet" + "</td>";
            restString += "<td>" + df.format(((double) arr.get(i).getExecuted() - arr.get(i).getNoOfFailed()) / arr.get(i).getExecuted() * 100) + "%" + "</td>";
            restString += "</tr>";
        }

        return restString;
    }

    int totalKilled = 0, totalSurvived = 0, totalExceptions = 0, totalSyntaxErrors = 0;
    double mutationScore = 0;

    public String printmutationTable(String path, ArrayList<MutationResults> arr, ArrayList<ResultsForEachFile> arr3) {
        ArrayList<Boolean> arr3Checker = new ArrayList<Boolean>();
        for (int i = 0; i < fileCode.size(); i++) {
            arr3Checker.add(false);
        }
        String restString = "";
        for (int i = 0; i < arr.size(); i++) {
            totalKilled += arr.get(i).getKillMutant();
            totalSurvived += arr.get(i).getSurvivedMutants();
            totalExceptions += arr.get(i).getExceptions();
            totalSyntaxErrors += arr.get(i).getSyntaxErrors();
            restString += "<tr class=\"odd gradeX\">";
            restString += "<td>" + "<a href=\"" + arr.get(i).getFileName() + ".html\">" + arr.get(i).getFileName() + "</a>" + "</td>";
            restString += "<td>" + arr.get(i).getKillMutant() + "</td>";
            restString += "<td>" + arr.get(i).getSurvivedMutants() + "</td>";
            restString += "<td>" + arr.get(i).getExceptions() + "</td>";
            restString += "<td>" + arr.get(i).getSyntaxErrors() + "</td>";
            int total = arr.get(i).getKillMutant() + arr.get(i).getSurvivedMutants() + arr.get(i).getExceptions() + arr.get(i).getSyntaxErrors();
            restString += "<td>" + total + "</td>";
            if (arr.get(i).getKillMutant() == 0) {
                restString += "<td>" + 0 + "%" + "</td>";
            } else {
                double score = ((double) arr.get(i).getKillMutant() / (arr.get(i).getSurvivedMutants() + arr.get(i).getKillMutant())) * 100;
                restString += "<td>" + df.format(score) + "%" + "</td>";
            }

            restString += "</tr>";
            int x = -1;

            for (int j = 0; j < fileCode.size(); j++) {
                FileAsString fs = fileCode.get(j);
                if (fileCode.get(j).getFileName().equals(arr.get(i).getFileName())) {
                    x = j;
                    arr3Checker.set(x, true);
                    break;
                }
            }
            if (x != -1) {
                ArrayList<ResultsForEachFile> arr4 = new ArrayList<ResultsForEachFile>();
                for (int j = 0; j < arr3.size(); j++) {
                    if (arr3.get(j).getFileName().equals(fileCode.get(x).getFileName())) {
                        arr4.add(arr3.get(j));
                    }

                }
                FileResults fr = new FileResults(fileCode.get(x).getFileCode(), fileCode.get(x).getFileName(), arr4);
                GenerateReportForEachFile grf = new GenerateReportForEachFile(fr);
                grf.generateHtmlFile(path);
            }

        }
        //
        mutationScore = ((double) totalKilled / (totalKilled + totalSurvived)) * 100.0;
        for (int i = 0; i < arr3Checker.size(); i++) {
            if (!arr3Checker.get(i)) {
                restString += "<tr class=\"odd gradeX\">";
                restString += "<td>" + "<a href=\"" + fileCode.get(i).getFileName() + ".html\">" + fileCode.get(i).getFileName() + "</a>" + "</td>";
                restString += "<td>" + 0 + "</td>";
                restString += "<td>" + 0 + "</td>";
                restString += "<td>" + 0 + "</td>";
                restString += "<td>" + 0 + "</td>";
                restString += "<td>" + 0 + "</td>";
                restString += "<td>" + 0 + "%" + "</td>";
                restString += "</tr>";

                ArrayList<ResultsForEachFile> arr4 = new ArrayList<ResultsForEachFile>();
                FileResults fr = new FileResults(fileCode.get(i).getFileCode(), fileCode.get(i).getFileName(), arr4);
                GenerateReportForEachFile grf = new GenerateReportForEachFile(fr);
                grf.generateHtmlFile(path);
            }
        }

        return restString;
    }

    /**
     * @return the fileCode
     */
    public ArrayList<FileAsString> getFileCode() {
        return fileCode;
    }

    /**
     * @param fileCode the fileCode to set
     */
    public void setFileCode(ArrayList<FileAsString> fileCode) {
        this.fileCode = fileCode;
    }

}
